apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-pet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-pet-frontend
  template:
    metadata:
      labels:
        app: hello-pet-frontend
    spec:
      containers:
      - name: hello-pet-frontend
        image: 10.10.10.1:5000/hello-pet-frontend
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: hello-pet-secrets
            optional: true  # secret이 없어도 배포 가능하도록 설정
---
apiVersion: v1
kind: Service
metadata:
  name: hello-pet-frontend-service
spec:
  selector:
    app: hello-pet-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-pet-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "hello.pet"  # 접속에 사용할 도메인
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-pet-frontend-service
            port:
              number: 3000