apiVersion: v1
kind: Secret
metadata:
  name: hello-pet-secrets
type: Opaque
stringData:
  # 여기에 환경변수를 key: value 형태로 추가하세요
  # 예시:
  # NEXT_PUBLIC_API_URL: "http://your-api-url"
  # DATABASE_URL: "your-database-connection-string"
  # JWT_SECRET: "your-jwt-secret"

  # 주의: 실제 비밀 값을 커밋하지 마세요!
  # 이 파일은 .gitignore에 추가하거나
  # 실제 값은 별도로 관리하는 것을 권장합니다