apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hello-pet-frontend

build:
  # 로컬 Docker를 사용해 이미지 빌드
  local:
    push: true  # 로컬 레지스트리에 push
  artifacts:
    # 빌드할 이미지 정보
    - image: 10.10.10.1:5000/hello-pet-frontend
      context: ../../..
      docker:
        dockerfile: Dockerfile

manifests:
  # 배포할 쿠버네티스 매니페스트 파일
  rawYaml:
    - hello-pet-app.yaml
    - k8s-secret.yaml

deploy:
  # kubectl을 사용해 배포
  kubectl: {}

portForward:
  # 로컬 개발 시 포트 포워딩 설정
  - resourceType: service
    resourceName: hello-pet-frontend-service
    port: 3000
    localPort: 3000